"""05022026a

Revision ID: e89f8fec77de
Revises: 
Create Date: 2026-02-05 21:03:08.353556

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e89f8fec77de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=False)
    op.create_index(op.f('ix_otp_expires_at'), 'otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_is_used'), 'otp', ['is_used'], unique=False)

    op.create_table('scheduler_run',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_run_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_run_job_name'), 'scheduler_run', ['job_name'], unique=True)
    op.create_index(op.f('ix_scheduler_run_last_run_at'), 'scheduler_run', ['last_run_at'], unique=False)

    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    category_table = op.create_table('category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_predefined', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_is_predefined'), 'category', ['is_predefined'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    # Perform the bulk insert
    op.bulk_insert(category_table, [
        {"name": "License", "is_predefined": True},
        {"name": "Subscription", "is_predefined": True},
        {"name": "Service Contract", "is_predefined": True},
        {"name": "Warranty", "is_predefined": True}
    ])

    op.create_table('tracking_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('reminder_date', sa.Date(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_done', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_item_category_id'), 'tracking_item', ['category_id'], unique=False)
    op.create_index(op.f('ix_tracking_item_created_at'), 'tracking_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_item_is_done'), 'tracking_item', ['is_done'], unique=False)
    op.create_index(op.f('ix_tracking_item_reminder_date'), 'tracking_item', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_tracking_item_user_id'), 'tracking_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_item_user_id'), table_name='tracking_item')
    op.drop_index(op.f('ix_tracking_item_reminder_date'), table_name='tracking_item')
    op.drop_index(op.f('ix_tracking_item_is_done'), table_name='tracking_item')
    op.drop_index(op.f('ix_tracking_item_created_at'), table_name='tracking_item')
    op.drop_index(op.f('ix_tracking_item_category_id'), table_name='tracking_item')
    op.drop_table('tracking_item')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_is_predefined'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_scheduler_run_last_run_at'), table_name='scheduler_run')
    op.drop_index(op.f('ix_scheduler_run_job_name'), table_name='scheduler_run')
    op.drop_table('scheduler_run')
    op.drop_index(op.f('ix_otp_is_used'), table_name='otp')
    op.drop_index(op.f('ix_otp_expires_at'), table_name='otp')
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
